Exceptions ole
lithiumox-codam/irc pull request #20
Opened 2024-12-19 16:02 UTC by LithiumOx

2024-12-19 17:20 UTC, Max-Valk requested changes
revert alles behalve de extra checks en bot code

2024-12-19 17:20 UTC, Max-Valk commented on include/Codes.hpp
verkeerde format gebruikt

2024-12-19 17:20 UTC, Max-Valk commented on include/Exceptions.hpp
verkeerde format

2024-12-19 17:20 UTC, Max-Valk commented on include/General.hpp
verkeerde format

2024-12-19 17:20 UTC, Max-Valk commented on include/Server.hpp
onderdeel van een complete server rewrite die niet nodig is. zorg ervoor dat de extra checks voor de input in de oude code komen te staan in plaats van alle init functies op deze manier schrijven

2024-12-19 17:20 UTC, Max-Valk commented on include/User.hpp
zet de sterretje if check waar je een empty get nickname kan verwachten ipv de const & weghalen voor alle getnickname calls

2024-12-19 17:20 UTC, Max-Valk commented on src/Env.cpp
zet deze file terug, het was compleet overbodig om alle functies in deze file te rewriten en een nieuwe file hier voor aan te maken. zoals eerder gezegd, zet de init checks gewoon in de functies die hiervoor in deze file stonden

2024-12-19 17:20 UTC, Max-Valk commented on src/Parser.cpp
onnodige logging die al in IRStream staat

2024-12-19 17:20 UTC, Max-Valk commented on src/Server.cpp
ik dacht dat we dit al duidelijk gemaakt hadden maar de hele epoll handling en server initialization hoeft niet aangepast te worden. dit zijn allemaal onnodige changes die opnieuw getest zouden moeten worden. je kan dit niet zonder overleg aanpassen. dit is niet iets kleins wat geen impact heeft op de rest van de code. dit is letterlijk de basis die we al maanden gebruiken, en die al een keer eerder heel de werking van de server heeft verstoord.

2024-12-19 17:20 UTC, Max-Valk commented on src/ServerInit.cpp
zoals al eerder vermeld is dit een compleet onnodige rewrite. deze hele file moet weg en alle changes erin moeten gerevert worden

2024-12-19 17:20 UTC, Max-Valk commented on src/User.cpp
> +string User::getNickname() const {
again dit moet je niet veranderen in een van de meest gebruikte functies in heel de code waardoor nu iedere keer dat deze gecalled wordt een kopie van een string gemaakt wordt.

2024-12-19 17:20 UTC, Max-Valk commented on src/User.cpp
> +	if (nickname == "*") {
gebruik hier gewoon nickname.empty()

2024-12-19 17:20 UTC, Max-Valk commented on src/commands/KICK.cpp
een extra parse functie die onnodig is en tevens een verkeerde result geeft als er geen message wordt meegestuurd. haal dit compleet weg

2024-12-19 17:20 UTC, Max-Valk commented on src/main.cpp
revert

2024-12-20 13:15 UTC, olebol reviewed
check new commits for changes and explanations

2024-12-20 13:15 UTC, olebol commented on include/Codes.hpp
is wat make format doet

2024-12-20 13:15 UTC, olebol commented on include/Exceptions.hpp
is wat make format doet

2024-12-20 13:15 UTC, olebol commented on include/General.hpp
is wat make format doet

2024-12-20 13:15 UTC, olebol commented on include/Server.hpp
hier is letterlijk niks veranderd naast unused functies weggehaald, is alleen verschoven zodat ze bij elkaar staan

2024-12-20 13:15 UTC, olebol commented on include/User.hpp
Ik heb dit uiteraard gecheckt en het moet overal sterretje zijn if empty. Which means bij elke getNickname checken en sterretje neerzetten OR gewoon bij deze sterretje returnen if empty.

Omdat je daardoor "*" returned kan je geen reference returnen, en aangezien het geen reference is boeit const helemaal niet.

2024-12-20 13:15 UTC, olebol commented on src/commands/PASS.cpp
Als we * returnen in de getnickname kan de turnary weg

2024-12-20 13:15 UTC, olebol commented on src/commands/KICK.cpp
Inderdaad fout gemaakt, gefixt zie revised

vind wel dat het in een andere functie moet en for_each overbodig complicated toevoegt

2024-12-20 13:15 UTC, olebol commented on src/Parser.cpp
Dit is logging van de inkomende messages, dat gebeurde nog niet, maar als we het echt niet willen zal ik het weghalen

2024-12-20 13:15 UTC, olebol commented on src/User.cpp
> +string User::getNickname() const {
Ik heb dit uiteraard gecheckt en het moet overal sterretje zijn if empty. Which means bij elke getNickname checken en sterretje neerzetten OR gewoon bij deze sterretje returnen if empty.

Omdat je daardoor "*" returned kan je geen reference returnen, en aangezien het geen reference is boeit const helemaal niet.

2024-12-20 13:15 UTC, olebol commented on src/Server.cpp
> +			if ((event.events & EPOLLIN) == 0) {
Gecheckt en dit kan gebeuren maar betekent altijd dat het een error is, dus epoll error = server closen

2024-12-20 13:15 UTC, olebol commented on src/Server.cpp
Het staat een beetje door elkaar for some reason door git, maar als je checkt met de file op main zijn de epoll functies precies hetzelfde met de uitzondering van de exceptions die nu bij errors worden gegooid ipv exits

2024-12-20 13:15 UTC, olebol commented on src/ServerInit.cpp
De meeste functies komen uit Server, heb ze apart getrokken omdat de Server file zeer groot was en ik dacht dat dit een goede verdeling en groepering was, ik kan die functies in principe terugzetten maar zie niet helemaal in waarom, het veranderd niks.

Ik heb checks toegevoegd op plekken waar deze nog niet stonden, in both environment en init functies, aangezien de oorspronkelijke versie een core dump issue had.

Ik heb de overall environment parsing inderdaad aangepast, de defines kunnen weg die zijn ondertussen redelijk nutteloos in de current file. Check next commit.

Ik heb toegevoegd dat command line arguments prioriteit krijgen over environment, omdat je deze manually zet. De env file heb ik prioriteit laten nemen over de system environment, aangezien je die ook zelf zet en je deze duidelijk liever wilt gebruiken.

Ik heb toegevoegd dat het werkt zonder arguments te passen aan het programma.

Ik heb de overall environment parsing code leesbaarder, duidelijker gemaakt en meer structuur gegeven, zodat onze evaluators het zo snel mogelijk kunnen lezen en wij zo snel mogelijk kunnen zien waar de fout zit. Ik zal een revisie doen in de volgende commit die het nog iets opschoont. Reverten is iig niet de oplossing, want er zitten echt verbeteringen in, die tested zijn.

2024-12-20 13:15 UTC, olebol commented on src/Env.cpp
zie comment onder serverinit.cpp

2024-12-20 13:15 UTC, olebol commented on src/main.cpp
SIGKILL kan niet opgevangen worden.

De rest is veel overzichtelijker zo, maar kom vooral met suggesties

2025-01-08 13:25 UTC, Max-Valk approved these changes

2025-01-08 13:25 UTC, merged